platform :ios, '15.0'

target 'ExchangeConvertApp' do
  use_frameworks!
  
  # Shared KMP module
  pod 'shared', :path => '../shared'
  
  # Compose Multiplatform for hybrid UI
  # Note: Compose Multiplatform requires additional setup
  # See: https://github.com/JetBrains/compose-multiplatform-ios-template
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
